/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardecoratorpackage;

import java.text.DecimalFormat;

/**
 *
 * @author erins
 */
public class CarDecoratorJFrame extends javax.swing.JFrame {

    private Car car = new BasicCar();
    private String carDesc = "";
    private double carPrice;
    DecimalFormat format = new DecimalFormat("#.00");
    
    /**
     * Creates new form CarDecoratorJFrame
     */
    public CarDecoratorJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        awdCheckBox = new javax.swing.JCheckBox();
        leatherSeatsCheckBox = new javax.swing.JCheckBox();
        leatherTrimSeatsCheckBox = new javax.swing.JCheckBox();
        v6EngineCheckBox = new javax.swing.JCheckBox();
        v8EngineCheckBox = new javax.swing.JCheckBox();
        applyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select add-ons:");

        awdCheckBox.setText("All wheel drive");
        awdCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awdCheckBoxActionPerformed(evt);
            }
        });

        leatherSeatsCheckBox.setText("Leather seats");
        leatherSeatsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leatherSeatsCheckBoxActionPerformed(evt);
            }
        });

        leatherTrimSeatsCheckBox.setText("Leather trim seats");
        leatherTrimSeatsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leatherTrimSeatsCheckBoxActionPerformed(evt);
            }
        });

        v6EngineCheckBox.setText("V6 engine");
        v6EngineCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v6EngineCheckBoxActionPerformed(evt);
            }
        });

        v8EngineCheckBox.setText("V8 engine");
        v8EngineCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v8EngineCheckBoxActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(awdCheckBox)
                        .addComponent(jLabel1))
                    .addComponent(leatherSeatsCheckBox)
                    .addComponent(leatherTrimSeatsCheckBox)
                    .addComponent(v6EngineCheckBox)
                    .addComponent(v8EngineCheckBox)
                    .addComponent(applyButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(awdCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leatherSeatsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leatherTrimSeatsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v6EngineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v8EngineCheckBox)
                .addGap(18, 18, 18)
                .addComponent(applyButton))
        );

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setText("Base model: front wheel drive, v4 engine, cloth seats\nAdd-ons/upgrades:\n");
        textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void awdCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awdCheckBoxActionPerformed
        if(awdCheckBox.isSelected())
        {
            car = new AllWheelDrive(car);
        }
    }//GEN-LAST:event_awdCheckBoxActionPerformed

    private void leatherSeatsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leatherSeatsCheckBoxActionPerformed
        if(leatherSeatsCheckBox.isSelected())
        {
            car = new LeatherSeats(car);
            leatherTrimSeatsCheckBox.setEnabled(false); // leather seats and leather trim seats are mutually exclusive
        }
        else
            leatherTrimSeatsCheckBox.setEnabled(true);        
    }//GEN-LAST:event_leatherSeatsCheckBoxActionPerformed

    private void leatherTrimSeatsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leatherTrimSeatsCheckBoxActionPerformed
        if(leatherTrimSeatsCheckBox.isSelected())
        {
            car = new LeatherTrimSeats(car);
            leatherSeatsCheckBox.setEnabled(false);
        }
        else
            leatherSeatsCheckBox.setEnabled(true);
    }//GEN-LAST:event_leatherTrimSeatsCheckBoxActionPerformed

    private void v6EngineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v6EngineCheckBoxActionPerformed
        if(v6EngineCheckBox.isSelected())
        {
            car = new V6Engine(car);
            v8EngineCheckBox.setEnabled(false); // v8 and v6 engines are mutually exclusive
        }
        else
            v8EngineCheckBox.setEnabled(true);
    }//GEN-LAST:event_v6EngineCheckBoxActionPerformed

    private void v8EngineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v8EngineCheckBoxActionPerformed
        if(v8EngineCheckBox.isSelected())
        {
            car = new V8Engine(car);
            v6EngineCheckBox.setEnabled(false);
        }
        else
            v6EngineCheckBox.setEnabled(true);
    }//GEN-LAST:event_v8EngineCheckBoxActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        // get price and description of the modified car and display it to the user
        carDesc = car.getDesc();
        carPrice = car.getPrice();
        textArea.append("Description: " + carDesc + "\nPrice: $" + format.format(carPrice));
    }//GEN-LAST:event_applyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarDecoratorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarDecoratorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarDecoratorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarDecoratorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarDecoratorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JCheckBox awdCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox leatherSeatsCheckBox;
    private javax.swing.JCheckBox leatherTrimSeatsCheckBox;
    private javax.swing.JTextArea textArea;
    private javax.swing.JCheckBox v6EngineCheckBox;
    private javax.swing.JCheckBox v8EngineCheckBox;
    // End of variables declaration//GEN-END:variables
}
